version: 2.1

jobs:
  integration-tests:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: "Update pip"
          command: pip install --upgrade pip setuptools
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  test-all:
    jobs:
      - integration-tests
