version: 2.1

jobs:
  integration-tests:
    environment:
      ODBC_DRIVER: Simba
    docker:
      - image: cimg/python:3.9
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Install spark odbc drivers"
          command: |
            sudo apt-get update && sudo apt-get install -y --no-install-recommends \
              g++ unixodbc-dev unzip libsasl2-modules-gssapi-mit
            curl https://databricks.com/wp-content/uploads/drivers-2020/SimbaSparkODBC-2.6.16.1019-Debian-64bit.zip -L -o /tmp/simba_odbc.zip
            unzip /tmp/simba_odbc.zip -d /tmp/
            sudo dpkg -i /tmp/SimbaSparkODBC-*/*.deb
            echo "[Simba]\nDriver = /opt/simba/spark/lib/64/libsparkodbc_sb64.so" | sudo tee -a /etc/odbcinst.ini
            rm /tmp/simba_odbc.zip
            rm -rf /tmp/SimbaSparkODBC*
            cat /etc/odbcinst.ini
      - run:
          name: "Install dbt"
          command: |
            pip install --upgrade pip setuptools
            pip install dbt-spark[ODBC] --upgrade --pre
            dbt --version
      - run:
          name: "Run tests"
          command: ./run_test.sh databricks
      - store_artifacts:
          path: integration_tests/logs

workflows:
  test-all:
    jobs:
      - integration-tests:
          context: profile-databricks
