version: 2.1

jobs:
  integration-tests:
    docker:
      - image: cimg/python:3.9
        user: root
    steps:
      - checkout
      - run:
          name: "Install spark odbc drivers"
          command: |
            apt-get update && apt-get install -y --no-install-recommends \\
              g++ \\
              unixodbc-dev \\
              unzip
      - run:
          name: "Update pip"
          command: pip install --upgrade pip setuptools
      - run:
          name: "Install dbt"
          command: "echo Hello, World!"

workflows:
  test-all:
    jobs:
      - integration-tests
