version: 2.1

jobs:
  integration-tests:
    docker:
      - image: cimg/python:3.9
        user: root
    steps:
      - checkout
      - run:
          name: "Install spark odbc drivers"
          command: |
            apt-get update && apt-get install -y --no-install-recommends \
              g++ unixodbc-dev unzip
            curl https://databricks.com/wp-content/uploads/drivers-2020/SimbaSparkODBC-2.6.16.1019-Debian-64bit.zip -L -o /tmp/simba_odbc.zip
            unzip /tmp/simba_odbc.zip -d /tmp/
            dpkg -i /tmp/SimbaSparkODBC-*/*.deb
            echo "[Simba]\nDriver = /opt/simba/spark/lib/64/libsparkodbc_sb64.so" >> /etc/odbcinst.ini
            rm /tmp/simba_odbc.zip
            rm -rf /tmp/SimbaSparkODBC*
      - run:
          name: "Update pip"
          command: pip install --upgrade pip setuptools
      - run:
          name: "Install dbt"
          command: "echo Hello, World!"

workflows:
  test-all:
    jobs:
      - integration-tests
